#!/bin/bash
BATCH_SIZE=128
WORKER_NUMBER=16
LEARNING_RATE=0.1

GPU_ID=4,5,6,7

CUDA_VISIBLE_DEVICES=$GPU_ID python train.py -m AF2 -mpath checkpoint/MNet_epoch_995 -bs $BATCH_SIZE -lr $LEARNING_RATE -nw $WORKER_NUMBER -mGPUs